import React from 'react';
import ReactDOM from 'react-dom';
import configureStore from './store/store';
import Root from './components/root';

const cb = () => {

    // Retrieve current user info that is bootstrapped to window by Rails in order to persist sessions in redux state.
    let preloadedState = {};
    if (window.currentUser) {
        preloadedState = {
            sessions: { 
                id: window.currentUser.id 
            },
            entities: {
                users: {
                    [window.currentUser.id]: window.currentUser
                }
            }
        };
    }
    const store = configureStore(preloadedState);
    delete window.currentUser;

    // Hook into root element generated by Rails.
    const root = document.getElementById("root");

    ReactDOM.render(<Root store={store} />, root);
};

// Execute callback only once DOM content successfully loads.
document.addEventListener("DOMContentLoaded", cb);